apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: webapp
  namespace: demo-kargo-app
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/ansilh/rollouts-demo
      imageSelectionStrategy: SemVer
