apiVersion: v2
name: kgateway
description: Install KGateway
type: application
version: v2.0.5
appVersion: "v1.1.0"

dependencies:
  - name: kgateway
    version: v2.0.5
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
