apiVersion: v2
name: kargo-lab
description: Install Kargo in the tools cluster
type: application
version: 0.0.1
appVersion: "v1.9.2"

dependencies:
  - name: kargo
    version: 1.9.2
    repository: oci://ghcr.io/akuity/kargo-charts
