argo-cd:
  configs:
      # Argo CD RBAC policy configuration
      ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
      rbac:
        # -- Create the argocd-rbac-cm configmap with ([Argo CD RBAC policy]) definitions.
        # If false, it is expected the configmap will be created by something else.
        # Argo CD will not work if there is no configmap created with the name above.
        create: false

        # -- Annotations to be added to argocd-rbac-cm configmap
        annotations: { }

        # -- The name of the default role which Argo CD will falls back to, when authorizing API requests (optional).
        # If omitted or empty, users may be still be able to login, but will see no apps, projects, etc...
        policy.default: ''

        # -- File containing user-defined policies and role definitions.
        # @default -- `''` (See [values.yaml])
        policy.csv: |
          g, lab-admins, role:admin

        scopes: "[groups]"
