apiVersion: v2
name: ai-argocd
description: Install argoCD in the tools cluster
type: application
version: 0.0.1
appVersion: "v1.1.0"

dependencies:
  - name: argo-cd
    version: 7.9.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version:  2.0.2
    repository: https://argoproj.github.io/argo-helm