apiVersion: v2
name: argocd-lab
description: Install ArgoRollout in all clusters
type: application
version: 0.0.1
appVersion: "v1.1.0"

dependencies:
  - name: argo-rollouts
    version: 2.40.6
    repository: https://argoproj.github.io/argo-helm
