apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "demo-kargo-app.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - backendRefs:
        - name: {{ include "demo-kargo-app.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 100
          group: ""
          kind: Service
        - name: {{ include "demo-kargo-app.fullname" . }}-canary
          port: {{ .Values.service.port }}
          weight: 0
          group: ""
          kind: Service
        matches:
        - path:
            type: PathPrefix
            value: /
